export const INACTIVITY_TIMEOUT_MS = 20 * 60 * 1000;
export const NO_OF_RECORDS_PER_PAGE_INDIVIDUAL = 25;
export const SHOW_RECORDS_PER_PAGE_GLOBAL_SEARCH = 5;
export const SHOW_RECORDS_PER_PAGE_GLOBAL_SEARCH_CONTACTS = 3;
export const SHOW_RECORDS_PER_PAGE_CONTACTS = 5;
export const NUMBER_OF_CHARACTERS_IN_SEARCH_BAR = 2;
export const BATCH_PER_PAGE = 10;
export const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
export const phoneRegex = /^\d{10}$/;
export const AUTO_SAVE_INTERVAL_MS = 30000;

export const ROLES = {
  ADMIN: "ADMINISTRATOR"
}

// Role mapping between API config values and display names
export const ROLE_DISPLAY_MAP: Record<string, string> = {
  VIEWER: "Viewer",
  REQUESTOR: "Requestor",
  CONFIGURATOR: "Configurator",
  CONFIGURATION_MANAGER: "Configuration Manager",
  QUALITY_REVIEWER: "Quality Reviewer",
  QUALITY_REVIEW_MANAGER: "Quality Review Manager",
  ADMIN: "Admin",
};

// Helper function to get role display name from config value
export const getRoleDisplayName = (roleId: string): string => {
  return ROLE_DISPLAY_MAP[roleId] || roleId;
};

export const VALIDATION_REGEX = {
  EMAIL: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  PHONE: /^\d{10}$/,
  ONLY_SPACES: /^\s+$/,
  ONLY_NUMERIC: /^\d+$/,
  USERNAME: /^[\p{L}\p{M}\s'-]+$/u,
};

// Helper function to get config value from display name
export const getRoleConfigValue = (displayName: string): string => {
  const entry = Object.entries(ROLE_DISPLAY_MAP).find(
    ([_, value]) => value === displayName
  );
  return entry ? entry[0] : displayName;
};

export const LABELS = {
  marketing: {
    PRINT_PHONE: "Print phone",
    PRINT_URL: "Print URL",
    WEB_URL: "Web URL",
    PRIMARY_MARKETING_CONTACT: "Primary marketing contact",
    CONTACT: "Contact",
    MARKETING_SITE_USER_TELEMED: "Marketing site user - Telemed",
    ENROLLMENT_SURVEY_NAME: "Enrollment communications survey name",
    ENROLLMENT_SURVEY_TYPE: "Enrollment communications survey type",
    SURVEY_STATUS: "Survey status",
    SURVEY_STATUS_UPDATED_DATE: "Survey status updated date",
    DIRECT_MAIL_OPT_IN: "Direct mail opt in?",
    INCENTIVES_OPT_IN: "Incentives opt in?",
    EMAIL_OPT_IN: "Email opt in?",
    OUTBOUND_CALLS_OPT_IN: "Outbound calls opt in?",
    TEXT_OPT_IN: "Text opt in?",
    LABEL_MARKETING_SITE_USER_TOOLTIP: "This selection will enable this contact to have marketing site access for this organization.",
    LABEL_PRIMARY_MARKETING_CONTACT_TOOLTIP: "This selection is to indicate who the primary contact for marketing decisions is. This will NOT enable Marketing Site User access. Please add this contact as a ‘Marketing Site User’ as applicable."
  },
  reporting: {
    REPORT_SETTINGS: "Standard reports",
    REPORT_TYPE: "Report type",
    REPORT_SORTING: "Report sorting",
    EMAIL_CONTENT_VERSION: "Email content version",
    DELIVERY_FREQUENCY: "Delivery frequency",
    REPORT_VERSION: "Report version",
    REPORT_EFFECTIVE_START_DATE: "Report effective start date",
    REPORT_EFFECTIVE_END_DATE: "Report effective end date",
    REPORT_TEMPLATE: "Report template",
    REPORT_RECIPIENTS: "Report recipients",
    EMAIL_RECIPIENT: "Email Recipient",
    EMAIL_ADDRESS: "Email address",
    NO_MATCH_CREATE_NEW_CONTACT: "No match? Create new contact for",
    ADD_REPORT: "Add report",
    REMOVE_REPORT: "Remove report",
    CREATE_NEW_CONTACT: "Create new contact",
    USE_EMAIL_ONLY: "Use email only",
    BACK_TO_SEARCH: "Back to search",
    CREATE_AND_ADD_TO: "Create and Add to",
    EMAIL: "Email",
    FIRST_NAME: "First Name",
    LAST_NAME: "Last Name",
    CONTACT_NOTE_TITLE: "Note",
    CONTACT_NOTE_MESSAGE:
      "If first and last names are not provided, the contact will display using the email address.",
    CONTACT_EMAIL_REQUIRED: "Email is required.",
    CONTACT_EMAIL_INVALID: "Enter a valid email address.",
    CONTACT_EMAIL_EXISTS: "A contact with this email already exists.",
  },
  grpGeneralSetting: {
    CM_CODE_ASSIGNMENT_ID: "CM Code assignment ID",
    CODE: "Code",
    CMC_RECORD_TYPE: "CMC record type",
    USED_FOR_RESGISTRATION: "Used for registration",
    ACTIVE: "Active?",
    ACCOUNT: "Account",
    CMC_ASSOCIATION_ID: "CMC association ID",
    RECORD_TYPE: "Record type",
    CMC_CODE: "CMC code",
    PROGRAM_NUMBER: "Program number",
    PROGRAM_OVERVIEW_NAME: "Program overview name",
    ROUTING_RULE: "Routing rule",
    ID: "ID",
    DATE_TIME: "Date/time",
    CHANGED_BY: "Changed by",
    SERVICE: "Service",
    PROMOTION: "Promotion",
    PROMOTION_TYPE: "Promotion type",
    FAMILY: "Family",
    SERVICE_SPECIALITIES: "Service Specialties",
    INTERVAL: "Interval",
    PER_INTERVAL: "Per interval",
    DISCOUNT_TYPE: "Discount Type",
    DATE_ADDED: "Date added",
    CURRENT_START_DATE: "Current start date",
    CURRENT_END_DATE: "Current end date",
    LABEL_GROUP_NAME: "Group name (Admin)",
    LABEL_CLIENT_ACCOUNT_LCRM_TELADOC: "Client account (LCRM-teladoc)",
    LABEL_CLIENT_ACCOUNT_LCRM_LIVONGO: "Client account (LCRM-livongo)",
    LABEL_ACCOUNT: "Account (Client Overview)",
    LABEL_LEGACY_GROUP_ID: "Legacy group ID",
    LABEL_GROUP_ID: "Group ID",
    LABEL_REVENUE_BUCKET: "Revenue bucket",
    LABEL_LINE_OF_BUSINESS: "Line of business",
    LABEL_NAMESPACE: "Namespace",
    LABEL_CLIENT_MANAGER: "Client manager",
    LABEL_STATUS: "Status",
    LABEL_EFFECTIVE_START_DATE: "Effective start date",
    LABEL_EFFECTIVE_END_DATE: "Effective end date",
    LABEL_TERMINATION_DATE: "Termination date",
    LABEL_CLIENT_OVERVIEW_NAME: "Client overview name",
    LABEL_CLIENT_OVERVIEW_STATUS: "Client overview status",
    LABEL_CONTRACT_PATH: "Contract path",
    LABEL_DOMESTIC_COUNTRY: "Domestic country",
    LABEL_SOLD_TO_ACCOUNT_UUID: "Sold to account GUID",
    LABEL_ONEAPP_ACCESS: "OneApp access",
    LABEL_HEALTH_ASSISTANT: "Health assistant",
    LABEL_ONEAPP_START_DATE: "OneApp start date",
    LABEL_MIGRATION_GROUP_NUMBER: "Migration group number",
    LABEL_LIVONGO_REGISTRATION_CODE: "Livongo registration code",
    LABEL_LIVONGO_CLIENT_MEMBER_CODE: "Livongo client member code",
    LABEL_ENABLE_CHRONIC_CARE_REFERRAL: "Enable chronic care referrals",
    LABEL_ENABLE_CORE_ADMIN_IMPORT: "Enable core admin import?",
    LABEL_REGISTRATION_NAME: "Registration name",
    LABEL_CCM_REGISTRATION_ADDRESS_TYPE: "CCM registration address type",
    LABEL_CHRONIC_CARE_POPULATION_TYPE: "Chronic care population type",
    LABEL_CHRONIC_CARE_POPULATION_COVERAGE: "Chronic care population coverage",
    LABEL_WELCOME_KITS_SHIPPED_BY_UPS_NOT_FEDEX:
      "Welcome kits shipped by UPS, not FedEx",
    LABEL_BENEFIT_RESTRICTION_CODE: "Benefit restriction code",
    LABEL_REGISTRATION_GROUP_CODE: "Registration group code",
    LABEL_GROUP_TYPE: "Group type",
    LABEL_BRAND_CODE: "Brand code",
    LABEL_STATE: "State",
    LABEL_SOLD_TO_ACCOUNT_NAME: "Sold to account name",
    LABEL_CCM_EXTERNAL_TAGS: "CCM external tags",
    LABEL_NOTES_INTERNAL: "Notes (internal)",
    LABEL_NOTES_EXTERNAL: "Notes (external)",
    LABEL_COMPANY_TAGS: "Company tags",
    LABEL_ANY_SPECIAL_INSTRUCTION: "Any special instructions",
    LABEL_SEND_MEMBER_RESOLUTION_LETTER: "Send member resolution letter",
    LABEL_SEND_UTILIZATION_LETTER: "Send utilization letter",
    LABEL_SEND_FRAUD_WASTE_AND_ABUSE_TERM_LETTER:
      "Send fraud, waste and abuse term letter",
    LABEL_SEND_PROBLEM_MEMBER_LETTER: "Send problem member letter",
    LABEL_HHS_ACCESS: "HHS access",
    LABEL_ENABLE_HEALTH_DATA_VISUALIZATION: "Enable health data visualization",
    LABEL_ALLOWED_NO_USERNAME_PASSWORD: "Allowed no username/password",
    LABEL_DUAL_ACCESS: "Dual access",
    LABEL_WEB_ACCESS: "Web access",
    LABEL_MOBILE_ACCESS: "Mobile access",
    LABEL_ALLOW_CONVERSION_TO_RETAIL: "Allow conversion to retail",
    LABEL_VIP_MEMBERS: "VIP members",
    LABEL_ENABLE_GEO_FENCING: "Enable geo-fencing",
    LABEL_RESTRICTED_PHI_ACCESS: "Restricted PHI access",
    LABEL_CCM_MULTIFACTOR_AUTHENTICATION: "CCM multifactor authentication",
    LABELS_MYSTRENGTH_GLOBAL_ACCESS_CD: "myStrength global access code",
    LABEL_ALLOW_REGISTRATIONS_VIA_CALL_CENTER:
      "Allow registrations via call center",
    LABEL_ALLOW_CONSULTATION_REQUESTS_VIA_CALL_CENTER:
      "Allow consultation requests via call center",
    LABEL_SEND_PROMO_CODE: "Send promo code",
    LABEL_REQUIRE_SECURITY_QUESTIONS_COUNT: "Require security questions count",
    LABEL_ENABLE_RESTRICTED_MEMBER_DOWNLOADS:
      "Enable restricted member downloads",
    LABEL_LINK_EXPIRATION_TIME_HOURS: "Link expiration time hours",
    LABEL_DATE_OF_BIRTH_CAN_BE_NULL: "Date of birth can be null",
    LABEL_ENABLE_WELLNESS_CONTENT: "Enable wellness content",
    LABEL_HIDE_SEXUAL_ORIENTATION_GENDER_IDENTITY_QUESTIONS:
      "Hide sexual orientation and gender identity questions?",
    LABEL_SEND_CCR_TO_PCP: "Send CCR to PCP",
    LABEL_DISABLE_PATIENT_EXCUSE_NOTE: "Disable patient excuse note",
    LABEL_IN_HOME_RX_DELIVERY: "In home Rx delivery",
    LABEL_TWO_STEP_AUTHENTICATION: "Two step authentication",
    LABEL_TWO_STEP_MAIL: "Two step Email",
    LABEL_TWO_STEP_SMS: "Two step SMS",
    LABEL_TWO_PHONE_CALL: "Two step Phone Call",
    LABEL_STANDARD_SERVICE_LEVEL: "Standard service level",
    LABEL_VIP_SERVICE_LEVEL: "VIP service level",
    LABEL_SLA_WAIVE_VISIT_FEE_IF_MISSED: "SLA - waive visit fee if missed",
    LABEL_PERFORMANCE_GUARANTEE: "Performance guarantee",
    LABEL_ROLE_TYPE: "Role type",
    LABEL_MEMBER_GROUP_NAME: "Member group name",
    LABEL_SOURCE_ACCOUNT: "Source account",
    LABEL_MEMBER_GROUP: "Member group",
    LABEL_MEMBER_GROUP_STATUS: "Member group status",
    LABEL_DUPLICATE_KEY: "Duplicate key",
    LABEL_CLINICAL_MODEL: "Clinical model",
    LABEL_CLINICAL_DATA_SHARING_ACCESS: "Clinical data sharing access",
    LABEL_CLINICAL_REFERRALS: "Clinical referrals",
    LABEL_CLINICAL_MODEL_DETAILS: "Clinical model details",
    LABEL_MEMBER_SUPPORT_URL: "Member support URL",
    LABEL_MEMBER_SUPPORT_PHONE: "Member support phone",
    CMC_USED_FOR_REGISTRATION_LABEL: "CMC used for registration",
    EFFECTIVE_DATE_LABEL: "Effective date",
    DEACTIVATED_DATE_LABEL: "Deactivated date",
    LAST_MODIFIED_BY_LABEL: "Last modified by",
    ORGANIZATIONS_LABEL: "Organization(s)",
    GROUPS_LABEL: "Group(s)",
  },
  grpBilling: {
    LABEL_MEMBERSHIP_FEE_TYPE: "Membership fee type",
    LABEL_CONSULT_BILLING_METHOD: "Consult billing method",
    LABEL_BILL_TO: "Bill to",
    LABEL_BILL_TO_ACCOUNT: "Bill to account",
    LABEL_BILL_TO_ACCOUNT_GUID: "Bill to account GUID",
    LABEL_PAYERS: "Payers",
    LABEL_TELADOC_TO_REFUND_MEMBERS: "Teladoc to refund members?",
    LABEL_CONSULTS_INCLUDED: "Consults included",
    LABEL_INCLUDE_CCM_PEPM_PRODUCT: "Include CCM PEPM product in the invoice",
    LABEL_PURCHASE_ORDER_NUMBER: "Purchase order number",
    LABEL_PURCHASE_ORDER_REQUIRED: "Purchase order required",
    LABEL_BILLING_PARTNER: "Billing partner",
    LABEL_BILLING_METHOD: "Billing method",
    LABEL_BILLING_POINT_OF_CONTACT: "Billing point of contact",
    LABEL_HIPAA_COVERED_ENTITY: "HIPAA covered entity",
    LABEL_DETAILED_INVOICE: "Detailed invoice?",
    LABEL_DETAILED_INVOICE_RECIPIENTS: "Detailed invoice recipients",
    LABEL_DETAILED_INVOICE_TAGS: "Detailed invoice tags",
    LABEL_BILLING_ADDRESS: "Billing address",
    LABEL_PAYMENT_TERMS: "Payment terms",
    LABEL_PRICING_MODEL: "Pricing model",
    LABEL_BUNDLED_PRICING_DISCOUNT: "Bundled pricing discount",
    LABEL_PRORATED_ENROLLMENT: "Prorated enrollment",
    LABEL_FAST_START_CREDIT_OFFERED: "Fast start credit offered",
    LABEL_FAST_START_CREDIT_TYPE: "Fast start credit type",
    LABEL_FAST_START_PARTICIPATION_RATE: "Fast start participation rate",
    LABEL_FAST_START_LAUNCH_DATE: "Fast start launch date",
    LABEL_FAST_START_CLOSE_DATE: "Fast start close date",
    LABEL_FAST_START_CUSTOM: "Fast start custom",
    LABEL_CONTRACT_TYPE: "Contract type",
    LABEL_LEGAL_NAME: "Legal name",
    LABEL_CONTRACT_EFFECTIVE_DATE: "Contract effective date",
    LABEL_CONTRACT_TERMINATION_DATE: "Contract termination date",
    LABEL_BAA_SIGNED: "BAA signed?",
    LABEL_MARKETING_AND_DOPS_REQUIREMENTS: "Marketing and DOPS requirements?",
    LABEL_ACCOUNT_HAS_SLAS: "Account has SLAs?",
    LABEL_SLA_DETAILS: "SLA details",
    LABEL_DAYS_NOTICE_FOR_TERMINATION: "Days notice for termination",
    LABEL_TERMINATION_FOR_CONVENIENCE: "Termination for convenience?",
    LABEL_DAYS_NOTICE_FOR_TERM_FOR_CONVENIENCE:
      "Days notice for term for convenience",
    LABEL_BILL_EARLY_TERMINATION_THROUGH_CLAIMS:
      "Bill early termination through claims",
    LABEL_CUSTOMER_SIGNED_DATE: "Customer signed date",
    LABEL_COMPANY_SIGNED_DATE: "Company signed date",
    LABEL_UNIQUE_CONTRACT_TERMS: "Unique contract terms",
    LABEL_IS_THERE_A_LAPSED_USER_CLAUSE: "Is there a lapsed user clause",
    LABEL_LAPSED_CLAUSE_CLAIMS_DATA: "Lapsed clause: claims data",
    LABEL_LAPSED_CLAUSE_MULTI_CHANNEL_MARKETING:
      "Lapsed clause: multi-channel marketing",
    LABEL_LAPSED_CLAUSE_USE_OF_INCENTIVES: "Lapsed clause: use of incentives",
    LABEL_LAPSED_CLAUSE_OPTIMIZED_ENROLLMENT_PLAN:
      "Lapsed clause: optimized enrollment plan",
  },
  grpMarketing: {
    SERVICE_BRAND: "Service brand",
    MARKETING_SITE_USER: "Marketing site user",
    MARKETING_SITE_ACTIVE_USER_FOR_CCM_PROGRAM:
      "Marketing site - active user for CCM program?",
    MARKETING_SITE_ACTIVE_USER_FOR_TELEMED_PROGRAM:
      "Marketing site - active user for Telemed program?",
    MARKETING_SITE_USER_CCM: "Marketing site user - CCM",
    MARKETING_SITE_USER_TELEMED: "Marketing site user - Telemed",
    LOGO_FILE_NAME: "Logo file name",
    LOGO_TAG: "Logo tag #",
    LOGO_TAG_ID: "Logo tag #ID",
    LOGO_1: "Logo 1",
    LOGO_1_ID: "Logo 1_ID",
    LOGO_3: "Logo 3",
    LOGO_3_ID: "Logo 3_ID",
    LOGO_4: "Logo 4",
    LOGO_4_ID: "Logo 4_ID",
    CO_BRAND_WITH_LOGO: "Co-brand with logo",
    TRI_BRAND_WITH_LOGO: "Tri-brand with logo",
    ALT_LOGO_1: "Altlogo1",
    ALT_LOGO_1_ID: "Altlogo1 ID",
    ALT_LOGO_2: "Altlogo2",
    ALT_LOGO_2_ID: "Altlogo2 ID",
    LOGO_TILE: "Logo tile",
    LOGO_DESCRIPTION: "Logo description",
    SFMC_ID: "SFMC ID",
    CURRENCY_ISO_CODE: "Currency ISO code",
    FILE_EXTENSION: "File extension",
    CLIENT_LOGO_LINK: "Client logo link",
    LANGUAGE: "Language",
    HEALTH_BENEFIT_LANGUAGE: "Health benefit language",
    PREFERRED_ELIGIBILITY_LANGUAGE: "Preferred eligibility language",
    TESTING_PERMISSION: "Testing permission",
    MODELING_PERMISSION: "Modeling permission",
    REGISTRATION_ENROLLMENT_ENGAGEMENT_TIER:
      "Registration/enrollment engagement tier",
    REGISTRATION_ENROLLMENT_JOURNEY: "Registration/enrollment journey",
    ONGOING_REGISTRATION_ENROLLMENT_JOURNEY:
      "Ongoing registration/enrollment journey",
    RECEIVING_CLAIMS_DATA_FOR_TELEMED_PROGRAMS:
      "Receiving claims data from Telemed programs?",
    WK_TEMPLATE: "Wk template",
    CARD_NAME: "Card name",
    CLIENT_ACCOUNT_LOCATION: "Client account location",
    MK_CONSULT_AREA: "MK_consultarea",
    DISCLAIMER_TELADOC: "Disclaimer-teladoc",
    CLIENT_DISCLAIMER: "Disclaimer-client ",
    DISCLAIMER_CUSTOM: "Disclaimer-custom",
    SEND_CARD: "Send card",
    ACTIVE_DATE: "Active date",
    SHIPPING_CLASS: "Shipping class",
    COMPANY_COPY: "Company copy",
    CMS_CODE: "CMS code",
    WK_CARD_INCLUDES_LOGO: "WK card includes logo?",
    MK_WELCOME_MESSAGE: "MK-welcome message",
    MK_ID_CARD_FRONT_1: "MK_ID card front 1",
    MK_ID_CARD_FRONT_2: "MK_ID card front 2",
    WK_MAIL_TO: "WK mail-to",
    WK_MAIL_TO_ADDRESS: "WK mail-to address",
    CONSULT_MESSAGE: "Consult message",
    CONSULT_MESSAGE_ON_WELCOME_LETTER: "Consult message on welcome letter?",
    WELCOME_LETTER_CONSULT_MESSAGE: "Welcome letter consult message",
    WK_INCLUDES_INSERT: "WK-includes insert?",
    INSERT_DOCUMENT_NAME: "Insert document name",
    CLIENT_FORM_NUMBER: "Client form number",
    P360_BRAND_RELATIONSHIP: "P360 brand relationship",
    P360_URL: "P360 URL",
    VIRTUAL_FIRST_PLAN_NAME: "Virtual first plan name",
    VIRTUAL_FIRST_HEALTH_PLAN_SUMMARY: "Virtual first health plan summary",
    HEALTH_PLAN_BOILER_PLATE_COPY: "Health plan boiler plate copy",
    VIRTUAL_FIRST_HEALTH_PLAN: "Virtual first health plan",
    REFERRAL_REQUIRED: "Referral required",
    IS_VALID_MSU_GROUP: "Is valid MSU group",
    OUTREACH_STRATIFICATION: "Outreach stratification",
    OUTREACH_STRATIFICATION_DATE: "Outreach stratification date",
    CLIENT_ALLOWS_TARGETED_MARKETING: "Client allows targeted marketing?",
    CLIENTS_MUST_APPROVE_ASSETS: "Client must approve assets",
    EMPLOYEE_TITLE: "Employee title",
    MARKETING_NAME: "Marketing name",
    CLIENT_SENDS_OWN_MARKETING: "Does Client send out own marketing?",
    CLIENT_ABLE_TO_WHITELIST: "Client able to whitelist?",
    USE_CONTRACT_PATH_FOR_MARKETING: "Use contract path for marketing?",
    HOLD_ALL_MARKETING: "Hold all marketing",
    DATE_MARKETING_PUT_ON_HOLD: "Date marketing put on hold",
    READY_FOR_AUTOMATION: "Ready for automation",
    CAMPAIGN_LIFECYCLE_PARTICIPATION: "Campaign lifecycle participation",
    CAMPAIGN_TYPE: "Campaign type",
    CAMPAIGN_OPTIONS: "Campaign options",
    REMOVE_SPANISH: "Remove Spanish",
    COMMUNICATION_MODE: "Communication mode",
    EMAIL_OPT_IN: "Email opt-in",
    DIRECT_MAIL_OPT_IN: "Direct mail opt-in",
    OUTBOUND_CALLS_OPT_IN: "Outbound calls opt-in",
    TEXT_OPT_IN: "Text opt-in",
    INCENTIVES_OPT_IN: "Incentives opt-in",
    AT_NO_COST_TO_YOU_ALT_TEXT: "At no cost to you alt text",
    JOIN_ALT_TEXT: "Join alt text",
    GENERAL_ELIGIBILITY_SENTENCE: "General eligibility sentence",
    GENERAL_SPANISH_ELIGIBILITY_SENTENCE:
      "General spanish eligibility sentence",
    PAID_FOR_BY: "100% paid for by",
    LOWERCASE_REGISTRATION_CODE: "Lowercase registration code",
    REMOVE_NEW: "Remove 'new'",
    HEALTH_BENEFIT_ALT_TEXT: "Health benefit alt text",
    STRIPS_LANCETS_ALT_TEXT: "Strips and lancets alt text",
    GENERAL_DISCLAIMER: "General disclaimer",
    GENERAL_SPANISH_DISCLAIMER: "General spanish disclaimer",
    REMOVE_UNLIMITED: "Remove unlimited",
    NO_OEP_DIRECT_MAIL_INSERTS: "No OEP direct mail inserts",
    CCM_INCENTIVES_GIFT_CARDS: "CCM incentives: gift cards",
    CCM_INCENTIVES_GIFT_CARDS_DATE: "CCM incentives: gift cards date",
    CCM_INCENTIVES_GOODS_SERVICES: "CCM incentives: goods and services",
    CCM_INCENTIVES_GOODS_SERVICES_DATE:
      "CCM incentives: goods and services date",
    USE_FOR_ACTIVATION_USAGE: "Use for Actication/Usage?",
    TYPE_OF_INCENTIVE_TO_EXCLUDE:
      "Type of Incentive to Exclude",
    HOLD_MEMBER_MARKETING: "Hold member marketing",
    MEMBER_COMMS_NEED_CLIENT_APPROVAL: "Member comms need client approval",
    CLIENT_ALLOWS_AB_TESTING_OF: "Client allows A/B testing of",
    MARKETING_CHANNEL_TYPE: "Marketing channel type",
    UNION_CLIENT: "Union client",
    U18_MARKETING: "U18 marketing?",
    MARKETING_INCENTIVE_TYPE: "Marketing incentive type",
    PHONE_CAMPAIGN: "Phone campaign",
    SEND_GROUP_TO_VENDORS: "Send group to vendors",
    SEND_GROUP_TO_VENDORS_TOOLTIP:
      "Whether the group is sent to vendors for marketing use",
    LABEL_MARKETING_SITE_USER_TOOLTIP: "This selection will enable this contact to have marketing site access for this group.",
    LOGO_TAG_TOOLTIP: "Full logo ID required to search",
  },
  grpReporting: {
    REPORT_SETTINGS: "Report settings",
    REPORT_TYPE: "Report type",
    REPORT_SORTING: "Report sorting",
    EMAIL_CONTENT_VERSION: "Email content version",
    DELIVERY_FREQUENCY: "Delivery frequency",
    REPORT_VERSION: "Report version",
    REPORT_EFFECTIVE_START_DATE: "Report effective start date",
    REPORT_EFFECTIVE_END_DATE: "Report effective end date",
    REPORT_TEMPLATE: "Report template",
  },
  eligibilityClaims: {
    VENDOR_GROUP_ID: "Vendor group ID",
    EXTERNAL_GROUP_TYPE: "External group type",
    STATE_RESTRICTION: "State restriction",
    EFFECTIVE_START_DATE: "Effective start date",
    EFFECTIVE_END: "Effective end date",
    PAYER_ID: "Payer ID",
    PRIMARY_REGISTRATION_MEMBER_SOURCE: "Primary registration member source",
    ENABLE_CCM_COMBINED_ELIGIBILITY: "Enable CCM combined eligibility",
    DEPENDENT_REGISTRATION_MEMBER_SOURCE:
      "Dependent registration member source",
    MINIMUM_AGE: "Primary registration minimum age",
    DEPENDENT_MINIMUM_AGE: "Dependent minimum age",
    DEPENDENT_MAXIMUM_AGE: "Dependent maximum age",
    ALLOW_MINOR_REGISTRATION: "Allow minor registration",
    ELIGIBILITY_CONTACT: "Eligibility contact",
    REGISTRATION_FLOW_SCENARIOS: "CCM Registration flow scenarios",
    REGISTRATION_CUSTOMIZATIONS: "Registration customizations",
    LINK_TO_BOX_FOLDER_PHI_RELEASE: "Link to box folder - PHI release",
    PROGRAM_ELIGIBILITY_FLAG: "Program eligibility flag",
    IS_ELIGIBILITY_DRIVERITIZED: "Is eligibility driveritized?",
    ELIGIBILITY_VERIFICATION_METHOD: "Eligibility verification method",
    ELIGIBILITY_EXCEPTIONS_RULES: "Eligibility exceptions/rules",
    ELIGIBILITY_FILE_CADENCE: "Eligibility file cadence",
    LINKS_TO_ELIGIBILITY_VERIFICATION_FOLDER:
      "Links to eligibility verification folder",
    MONTHLY_ESCALATION_PATH: "Monthly escalation path",
    DISABLE_LIVE_PROGRAM_ELIGIBILITY_CHECK:
      "Disable live program eligibility check",
    ELIGIBLE_GROUP_IDS: "Eligible group IDs",
    MANUAL_CHECK: "Manual check",
    POPULATION_DATA_SOURCES: "Population data sources",
    ELIGIBILITY_TEAM_NOTES: "Eligibility team notes",
    SSO_PARTNER: "SSO partner",
    INCENTIVES_API_PARTNER: "Incentives API partner",
    INCENTIVES_API_START_DATE: "Incentives API start date",
    INCENTIVE_REPORTING_PARTNER: "Incentive reporting partner",
    MEMBER_SUPPORT_DETAILS: "Member support details",
    CVS_TDC_ELIGIBILITY_CRITERIA: "CVS/TDC eligibility criteria",
  },
  billings: {
    BILLING_ACCOUNT_GUID: "Billing account GUID",
    PAYMENT_TERMS: "Payment terms",
    BILLING_ENABLED_AT_ORG_LEVEL: "Billing enabled at this org level?",
    FINANCE_CATEGORY: "Finance category",
    FINANCE_CATEGORY_2: "Finance category 2",
    FINANCE_CATEGORY_LCRM: "Finance category LCRM",
    FINANCE_SUBCATEGORY: "Finance subcategory",
    BILLING_STREET: "Billing street",
    BILLING_CITY: "Billing city",
    BILLING_STATE_PROVINCE: "Billing state/province",
    BILLING_ZIP_POSTAL_CODE: "Billing ZIP/postal code",
    BILLING_COUNTY: "Billing county",
    BILLING_COUNTRY: "Billing country",
    BILLING_ADDRESS_VERIFIED: "Billing address verified",
    BILLING_ADDRESS: "Billing address",
    PRIMARY_BILLING_CONTACT_TELEMED: "Primary billing contact- Telemed",
    SECONDARY_BILLING_CONTACT_TELEMED: "Secondary billing contact- Telemed",
    NEW_PURCHASE_ORDER: "New purchase order",
    RISK_CONTRACTS: "Risk contracts",
    INVOICE_NAME: "Invoice name",
    INVOICE_PERSON_TYPE: "Invoice person type",
    INVOICE_DELIVERY: "Invoice delivery",
    DOES_CLIENT_SELF_REMIT: "Does client self remit?",
    ELIGIBLE_DAY_OF_MONTH: "Eligibility day of month",
    REGARDS_TO: "Regards to",
    INVOICE_EMAIL: "Invoice email",
    FIRST_NAME: "First name",
    LAST_NAME: "Last name",
    CLIENT_EXPECTS_ROI: "Client expects ROI",
    REQUIRED_DATA_FOR_ROI: "Required data for ROI",
    ESTIMATED_AVG_EMPLOYEE_WAGE: "Estimated avg employee wage",
    ESTIMATED_ER_COST: "Estimated ER cost",
    ESTIMATED_PCP_COST: "Estimated PCP cost",
    ESTIMATED_SPEC_COST: "Estimated spec cost",
    ESTIMATED_URGENT_CARE_COST: "Estimated urgent care cost",
  },
  generalSetting: {
    ORGANIZATION_NAME: "Organization name (Admin)",
    NAME_TELADOC: "Name (LCRM-Telemed)",
    NAME_LIVONGO: "Name (LCRM-CCM)",
    FRIENDLY_ACCOUNT_NAME: "Friendly account name",
    DOING_BUSINESS_AS: "Doing business as",
    PARENT_ACCOUNT: "Parent account",
    ACCOUNT_STATUS: "Account status",
    BENEFIT_RESTRICTION_CODE: "Benefit restriction code",
    RECORD_TYPE: "Record type",
    CLIENT_TYPE: "Client type",
    ACCOUNT_BUSINESS_TYPE: "Account business type",
    ACCOUNT_EFFECTIVE_START_DATE: "Account effective start date",
    ACCOUNT_EFFECTIVE_END_DATE: "Account effective end date",
    BUSINESS_REGION: "Business region",
    IS_EMPLOYER: "Is this organization an employer?",
    HAS_BROKER_OR_REFERRAL:
      "Is there a broker/referral company for this organization?",
    CLIENT_IMPLEMENTATION_MANAGER: "Client Implementation Manager",
    SALES_AGENT: "Sales Agent",
    CLIENT_OPERATIONS_MANAGER: "Client Operations Manager",
    CLIENT_MANAGERS: "Client Manager",
    PRIMARY_DAILY_CONTACT_LABEL: "Primary daily contact",
    PRIMARY_BILLING_CONTACT_LABEL: "Primary billing contact",
    SECONDARY_BILLING_CONTACT_LABEL: "Secondary billing contact",
    VENDOR_POINT: "Vendor point",
    CATEGORY: "Category",
    EFFECTIVE_START_DATE: "Effective start date",
    EFFECTIVE_END_DATE: "Effective end date",
    PHONE_NUMBER: "Phone number",
    WEBSITE: "Website",
    DESCRIPTION: "Description",
    NOTE: "Note",
    PRIMARY_DAILY_CONTACT: "Primary daily contact",
    PRIMARY_BILLING_CONTACT: "Primary billing contact",
    SECONDARY_BILLING_CONTACT: "Secondary billing contact",
    NUMBER_OF_EMPLOYEES: "Number of employees",
    COVERED_LIVES: "Covered lives",
    UNION_POPULATION: "Union population",
    ORG_HIERARCHY_ID: "Org hierarchy ID",
    BILLING_ORG_OF_INVOICE_RECIPIENT: "Billing org of the invoice recipient",
    ADDRESS_LINE_1: "Address line 1",
    ADDRESS_LINE_2: "Address line 2",
    CITY: "City",
    STATE: "State",
    POSTAL: "Postal",
    COUNTRY: "Country",
    FIRST_NAME: "First name",
    LAST_NAME: "Last name",
    ACCOUNT_NAME: "Account name (LCRM-Teladoc)",
    PHONE: "Phone",
    EMAIL: "Email",
    CONTACT_STATUS: "Contact status",
    CONTACT_ROLE: "Contact role",
    MAILING_STREET: "Mailing street",
    MAILING_CITY: "Mailing city",
    MAILING_COUNTY: "Mailing county",
    MAILING_COUNTRY: "Mailing country",
    MAILING_STATE: "Mailing state/province",
    MAILING_POSTAL_CODE: "Mailing ZIP/postal code",
    MAILING_COUNTRY_CODE: "Mailing country",
    PARTNER_ACCOUNT: "Partner account",
    PARTNER_RELATIONSHIP_TO_TELADOC: "Partner relationships to Teladoc",
    PARTNER_RELATIONSHIP_TYPE: "Partner relationships type",
    SERVICING_CONTRACT_TYPE: "Servicing contract type",
    CLIENT_ACCOUNT: "Client account",
    START_DATE: "Start date",
    END_DATE: "End date",
    CONTRACT_OVERVIEW_ASSOCIATED_TO_PARTNER_RELATIONSHIP: "Contract overview associated to partner relationship",
    HAS_BROKER: "Has broker",
    SALESFORCE_ID: "Salesforce ID",
    COMMISION_NAME: "Commision name",
    BROKER_FLAT: "Broker flat-rate",
    LOCATION_ID: "Location ID",
    LOCATION_NAME: "Location name",
    BROKER_FEE: "Broker fee",
    BROKER_CONTACT: "Broker contact",
    BROKER_FLAT_RATE: "Broker flat-rate",
    BROKER_PERCENTAGE: "Broker percentage",
    COMPOSITE_KEY: "Composite key",
    BROKER_LOCATION_ID: "Broker location ID",
    BROKER_LOCATION_NAME: "Broker location name",
    CHRONIC_CARE_BROKER_FLAT_RATE: "Chronic care broker flat rate",
    CHRONIC_CARE_BROKER_PERCENTAGE: "Chronic care broker percentage",
    CONTACT: "Contact",
    ORIGINAL_CONTRACT: "Original contract",
    CONTRACT_OPS_OWNER: "Contract ops owner",
    COPO_CONFIGURATION_TEAM_STATUS: "Configuration team status",
    CURRENT_CONTRACT_ID: "Current contract ID",
    CONTRACT_OPS_STAGE: "ContractOps Stage",
    CONTRACT_TAG_ASSIGNMENT_ID: "Contract tag assignment id",
    SEND_MEMBER_RESOLUTION_LETTER: "Send member resolution letter",
    SEND_PROBLEM_MEMBER_LETTER: "Send problem member letter",
    SEND_UTILIZATION_LETTER: "Send utilization letter",
    SEND_FRAUD_WASTE_AND_ABUSE_TERM_LETTER:
      "Send fraud, waste and abuse term letter",
    SEND_CCR_TO_PCP: "Send CCR to PCP",
    ALLOW_AUTHORIZED_CONSENTERS: "Allow authorized consenters",
    ALLOW_MANAGE_SUBSCRIPTIONS: "Allow manage subscriptions",
    APPLY_FLAG_FIELDS_TO_CHILDREN_GROUPS:
      "Apply flag fields to children groups",
    DISABLE_PATIENT_EXCUSE_NOTE: "Disable patient excuse note",
    CANCEL_DEPENDENTS: "Cancel dependents",
    CANCEL_PRIMARY: "Cancel primary",
    APPLY_REGISTRATION_FIELDS_TO_CHILDREN_GROUPS:
      "Apply registration fields to children groups",
    APPLY_SERVICE_FIELDS_TO_CHILDREN_GROUPS:
      "Apply service level fields to children groups",
    EXTERNAL_PLAN_SPONSOR_ID: "External plan sponsor ID",
    EXTERNAL_MARKET_SEGMENT: "External market segment",
    CONTRACT: "Contract",
  },
  products: {
    PRODUCT_AND_FEATURE: "Product and feature",
    MEMBERSHIP_FEE: "Membership fee",
    MEMBERSHIP_FEE_TYPE: "Membership fee type",
    TOTAL_VISIT_FEE: "Total visit fee",
    MEMBER_VISIT_FEE: "Member visit fee",
    VISIT_FEE: "Visit fee",
    AGE: "Min Age",
    EFFECTIVE_DATE: "Start date",
    TERM_DATE: "End date",
    GROUP: "Group",
    BUNDLE_TYPE: "Bundle type",
    MEMBERSHIP: "Membership",
    PRODUCT: "Product",
    PARTNER: "Partner",
    TRANSITION_TO: "Transition To",
    ADVANCE_ASSESSMENT: "Advance assessment",
    NUTRITION_PROMOTION: "Nutrition promotion",
    PROACTIVE_COACHING: "Proactive coaching",
    CLEAR_ALL: "Clear all",
    SHOW_RESULTS: "Show results",
    TERM_DATE_RANGE: "Term date range",
    EFFECTIVE_DATE_RANGE: "Effective date range",
    SERVICE_CATEGORY: "Service category",
    MINIMUM_AGE: "Minimum age",
  },
  editConfig: {
    CANCEL: "Cancel",
    START_EDITING: "Start editing",
    PLANNED_LAUNCH_DATE_TOOLTIP: "For changes that should take effect now, select today's date. To schedule changes, select the date they should take effect.",
    SCHEDULE_FOR_LATER_TOOLTIP: "Select a future date to schedule when this item will be sent to production.",
    SAVED: "Saved",
    SAVING: "Saving...",
    EDITING: "Editing",
  }
};

export const LOGIN = {
  WELCOME_MESSAGE: "Welcome to ",
  CLIENT_CONNECTION_CENTER: "Client Connection Center",
  SIGN_IN_SSO: "Sign in with SSO",
  ENTER_EDIT_MODE: "You are about to enter edit mode.",
  PLEASE_SET_PRIORITY_AND_CHOOSE_LAUNCH_DATE: "Please set the priority and choose when this update should go live.",
  PROGRESS_SAVED: "Your progress has been saved.",
  CONFIRM_SUBMIT: "By confirming, your updates will be submitted and a new task will be created.",
  CONFIRM_UPDATE: "Confirm the updates and send them to production today on ",
  ORG_BEING_EDITED: "This org is being edited by others.",
  OVERLAPPING_CHANGES_WARNING: "To help avoid conflicts, please limit overlapping changes. You’ll be able to review your updates before submitting.",
};

export const MODAL_MSSG = {
  UPLOAD_RULES: "Upload rules",
  UPLOAD_CSV: "Upload CSV file",
  UPLOAD_JSON: "Upload rules messages",
  UPLOAD_DRL_MSSG: "Upload your file in DRL format. The max file size is [TBD].",
  UPLOAD_JSON_MSSG: "Upload your file in JSON format. The max file size is [TBD].",
  ERR_CSV: "Please upload file in CSV format.",
  ERR_DRL: "Please upload file in DRL format.",
  ERR_JSON: "Please upload file in JSON format.",
  UPLOAD_CSV_MSSG: "Upload your file in CSV format. The max file size is 100MB.",
  ENTER_EDIT_MODE: "You are about to enter edit mode.",
  PLEASE_SET_PRIORITY_AND_CHOOSE_LAUNCH_DATE: "Please set the priority and choose when this update should go live.",
  PROGRESS_SAVED: "Your progress has been saved.",
  CONFIRM_SUBMIT: "By confirming, your updates will be submitted and a new task will be created.",
  CONFIRM_RESTORE: "By confirming, the version will be restored.",
  CONFIRM_ROLLBACK: "Confirm to rollback to the selected version.",
  CONFIRM_UPDATE: "Confirm the updates and send them to production today on ",
  ORG_BEING_EDITED: "This org is being edited by others.",
  GRP_BEING_EDITED: "This group is being edited by others.",
  OVERLAPPING_CHANGES_WARNING: "To help avoid conflicts, please limit overlapping changes. You'll be able to review your updates before submitting.",
  EXIT_EDIT_TITLE: "Exit edit mode?",
  EXIT_EDIT_MODAL_WARNING: "You're in the middle of editing configuration. If you leave now, your progress won't be saved.",
  CONFIRM_CANCEL_TASK: "Cancelling will discard any progress made. This action can't be undone.",
  CANCELATION_REASON: "Describe the reason to cancel.",
  CONFIRM_HOLD_TASK: "Confirm to put on hold until further action.",
  REVERT_TO_DRAFT_TITLE: "Revert to Draft?",
  REVERT_TO_DRAFT_CONTENT:
    "This task will be moved back to Draft to make additional changes. Once resubmitted, it will restart the approval workflow.",
  PUT_ON_HOLD_REASON: "Describe the reason to put on hold.",
  REVIEW_SUCCESS_MESSAGE: "This action will approve the update.",
  REVIEW_CONFIRM_TEXT: "By confirming, your review will be submitted and approve the update.",
  REVIEW_CHECKBOX_LABEL: "Confirm to approve the update and send it to the next stage.",
  REVIEW_REJECT_CONFIRM_TEXT: "By confirming, your review will be submitted and reject the update.",
  REVIEW_REJECT_CHECKBOX_LABEL: "Confirm to reject the update and send it back.",
  REFRESH_DATA_TITLE: "Refresh data",
  REFRESH_DATA_KEEPS_CHANGES: "Refresh to get the latest production data. We'll keep your changes.",
  REFRESH_DATA_REVIEW_CONFLICTS: "If any fields conflict, you'll review them before you submit.",
  RESOLVE_CONFLICTS_TITLE: "Resolve conflicts",
  CANNOT_SCHEDULE_TITLE: "Cannot schedule this update",
  CANNOT_SCHEDULE_CONFLICT: "Your update is in conflict with the latest production data.",
  CANNOT_SCHEDULE_RESOLVE_FIRST: "You must resolve before you can schedule for production.",
  CONFLICT_WITH_LATEST_PRODUCTION: "Your updates are in conflict with the latest production data.",
  CONFLICT_REVIEW_AND_SELECT: "Please review and select the value you want to apply to your submission.",
  // Configurator raising a rebuttal.
  REBUTTAL_WARNING_DESC: "This action will return it to the assigned reviewer.",
  SEND_REBUTTAL_CONFIRM_TEXT: "By confirming, your rebuttal will be submitted.",
  SEND_REBUTTAL_CHECKBOX_LABEL: "Confirm to send the rebuttal to the assigned reviewer.",
  // Reviewer completing the review of a rebuttal — mirrors the REVIEW_* copy.
  REBUTTAL_SUCCESS_MESSAGE: "This action will approve the rebuttal.",
  REBUTTAL_CONFIRM_TEXT: "By confirming, your review will be submitted and approve the rebuttal.",
  REBUTTAL_CHECKBOX_LABEL: "Confirm to approve the rebuttal.",
  REBUTTAL_REJECT_CONFIRM_TEXT: "By confirming, your review will be submitted and reject the rebuttal.",
  REBUTTAL_REJECT_CHECKBOX_LABEL: "Confirm to reject the rebuttal and send it back.",
  REBUTTAL_REASON_PLACEHOLDER: "Select rebuttal reason",
  REBUTTAL_COMMENTS_PLACEHOLDER: "Describe in details the reason for the rebuttal.",
  REQUIRED_FIELD_HINT: "indicates a required field",
  CONFLICT_WITH_SCHEDULED_UPDATES: "Your updates are in conflict with scheduled or production updates.",
  CONFLICT_SELECT_VALUE_TO_APPLY: "Select the value you want to apply to your submission.",
  CONFLICT_FIELDS_SYNCED_UP: "Those fields are synced up",
  CONFLICT_FIELDS_NOT_EDITED_BY_YOU: "These fields weren't edited by you. They changed in production or have upcoming scheduled changes.",
  CONFLICT_CONFIRM_SELECTION: "Confirm your selection:",
  CONFLICT_CONFIRM_REVIEWED: "I have reviewed the conflicts. I understand my submission will use the value(s) selected.",
  CONFLICT_WITH_PRODUCTION_DELTA: "Conflicting with production delta update",
  PRODUCTION_DELTA_UPDATED_ON: "Production delta updated on",
  CONFLICTS_RESOLVED: "Conflicts resolved.",
  CONFLICT_WITH_PENDING_CHANGES: "Your updates are in conflict with pending changes.",
  CONFLICT_SELECT_HOW_TO_PROCEED: "Select how to proceed.",
  CONFLICT_PENDING_SAME_FIELD: "Your draft changes the same field effective immediately.",
  CONFLICT_PENDING_SAME_DATE: "Your draft has the same launch date.",
  CONFLICT_KEEP_BOTH_LABEL: "Keep both changes",
  CONFLICT_CANCEL_THEIRS_LABEL: "Apply mine, cancel the other entry",
  CONFLICT_OVERWRITE_WARNING: "This will overwrite my updates",
  CONFLICT_HOW_TO_RESOLVE: "How would you like to resolve this?",
  CONFLICT_ADD_COMMENTS: "Add comments",
  CONFLICT_COMMENTS_PLACEHOLDER: "Explain the selection",
  CONFLICT_CONFIRM_REVIEWED_ABOVE: "By confirming, you have reviewed the above conflict.",
  CONFLICT_CONFIRM_RESOLUTION: "I have reviewed the conflicts and I confirm my resolution.",
  CHECKING_CONFLICTS_TITLE: "Checking for conflicts",
  CHECKING_CONFLICTS: "Comparing your updates against production and pending changes.",
}

export const RIBBON_MSSG = {
  DATA_SUCCESSFULLY_LOADED: "Data successfully loaded.",
  CSV_FILE_UPLOADED: "CSV file uploaded.",
  ALL_DATA_ADDED: "All data from your CSV file has been successfully added.",
  PROCESSING_DATA: "We're processing your data entries now.",
  FILE_VALIDATION_FAILED: "File validation failed",
  INVALID_TEMPLATE_FIELDS: "Your upload didn't meet the required format. Make sure it has the correct template fields.",
  SOME_DATA_COULDNT_BE_LOADED: "Some data couldn't be loaded.",
  CSV_FILE_CONTAINS_INVALID_ENTRIES: "Your CSV file contains invalid entries that weren't added. Download the error report to view details.",
  SOMETHING_WENT_WRONG: "Something went wrong while loading your data. ",
  PLEASE_REFRESH: "Please refresh and try again. If the issue continues, contact Service Desk.",
  UPLOAD_COMPLETE: "You can close this message and continue working while the upload completes. ",
  PLEASE_WAIT: "Please wait while the upload completes.",
  CANT_SAVE_REPORTING_RECIPIENTS: "Can't save reporting recipients.",
  REPORTING_RECIPIENTS_CANNOT_BE_SAVED: "Reporting recipients cannot be saved.",
  NEEDS_VERIFIED_TD_ACCOUNT: "needs a verified linked TD account first.",
  CONFLICT_WITH_PRODUCTION_TITLE: "Conflict with production data",
  CONFLICT_WITH_PENDING_TITLE: "Your updates are in conflict with pending changes.",
  CONFLICT_WITH_PRODUCTION_MESSAGE: "Production data changed while you were editing. Review the updates and choose what to submit.",
  CONFLICT_WITH_PENDING_MESSAGE: "You must resolve these conflicts that have the same field and launch date.",
  RESOLVE_CONFLICTS_BUTTON: "Resolve conflicts",
  MUST_REFRESH_BEFORE_SUBMIT: "Must refresh the data before you can continue to submit",
  MUST_RESOLVE_BEFORE_SUBMIT:"Must resolve the conflicts before you can continue to submit",
}

export const ERROR_MESSAGES = {
  NO_BILLING_DATA: "No billing data found.",
  NO_GENERAL_SETTINGS_DATA: "No general settings data found.",
  NO_OPPORTUNITIES_DATA: "No opportunities data found.",
  NO_ORGANIZATION_DATA: "No organization data found.",
  NO_REPORTING_DATA: "No reporting data found.",
  NO_MARKETING_DATA: "No marketing data found.",
  NO_ELIGIBILITY_DATA: "No eligibility data found.",
  SOMETHINGS_WRONG: "Something's wrong.",
  CHECK_CONFLICTS_FAILED: "Failed to check conflicts. Please try again.",
  RESOLVE_CONFLICTS_FAILED: "Failed to resolve conflicts. Please try again.",
  NO_ELIGIBILITY_AND_CLAIMS_DATA: "No eligibility and claims data found.",
  NO_HIERARCHY_DATA: "No hierarchy data found.",
  NO_MARKETING_GROUP_DATA: "No marketing group data found.",
  NO_PRODUCTS_DATA: "No products data found.",
  NO_REPORTING_GROUP_DATA: "No reporting group data found.",
  SOMETHING_WENT_WRONG: "Something went wrong while loading your data.",
  PLEASE_REFRESH:
    "Please refresh the page and try again. If the issue continues, contact Service Desk.",
  COMING_SOON: "Coming Soon",
  SOMETHING_UNDER_DEVELOPMENT:
    "This feature is currently being developed. Stay tuned for updates!",
  NOTHING_FOUND: "Nothing found",
  TRY_CHANGING_FILTERS_OR_KEYWORD: "Try changing your filters or keyword",
  NO_INACTIVE_BROKER: "No inactive broker",
  ONCE_A_BROKER_IS_INACTIVATED: "Once a broker is inactivated, it will appear here.",
  NO_ACTIVE_BROKER: "No active broker",
  ONCE_A_BROKER_IS_ACTIVATED: "Once a broker is activated, it will appear here.",
  NO_DATA: "No data available",
  NO_DATA_MSG: "There's no data to display right now.",
  NOT_AUTHORIZED: "You are not authorized to view this page",
  NEED_HELP: "Need help? Contact Service Desk.",
  NO_CONTACTS: "No contacts available",
  NO_CONTACTS_MSG: "There's no contacts to display right now.",
  AUTO_SAVE_RETRY_OR_SERVICE_DESK:
    "Please contact Service Desk or try again.",
  AUTO_SAVE_CONTACT_SERVICE_DESK_ONLY: "Please contact Service Desk.",
  COMMENT_TOO_SHORT: "Comment must be at least 10 characters long."
};

export const API_ENDPOINTS = {
  organization: "/client-configurations/organizations",
  opportunity: "/client-configurations/opportunities",
  groups: "/client-configurations/groups",
  contact: "client-configurations/contacts",
  syncStatus: "/client-configurations/refresh-status",
  sync: "/client-configurations/refresh",
  dataLoad: "source-data/load",
  fileUpload: "source-data/upload/file",
  batches: "source-data/batches",
  search: "client-configurations/search",
  contacts: "client-configurations/contacts/search",
  contactFilterSearch: "client-configurations/contact/filter/search",
  contactFilter: "client-configurations/contact/filter",
  suggestedSearch: "client-configurations/suggest",
  drlUpload: "rule/uploadRules",
  jsonUpload: "rule/uploadRuleErrorDetails",
  validate: "validate",
  roles: "roles",
  users: "users",
  audit: "/audit/logs",
  auth: "auth",
  children: "/children",
  billing: "/billing",
  generalSettings: "/generalSettings",
  generalSettingsGrp: "/general-settings",
  reporting: "/reporting",
  opportunities: "/opportunities",
  marketing: "/marketing",
  hierarchy: "/hierarchy",
  agr: "/allowed-group-relations",
  egr: "/external-group-relations",
  eligibilityAndClaims: "/eligibilityAndClaims",
  products: "/products",
  errors: "errors",
  statuses: "/statuses",
  status: "/status",
  killSwitch: "kill-switch",
  accountsSearch: "client-configurations/accounts/search",
  updateOrgAccount: "client-configurations/orgs",
  diffLibrary: "client-configurations/difference-checker",
  metadata: "client-configurations/metadata",
  approveTask: "client-configurations/tasks",
};

export const ADMIN_PAGE = {
  ADMIN_TITLE: "Welcome to the Admin Portal",
  DOWNLOAD_CSV: "Download CSV",
  UPLOAD_CSV: "Upload CSV",
  ADD_USER: "Add user",
  EDIT_USER: "Edit user",
  ACTIVE_USERS: "Show only active users",
  DOWNLOAD_TEMPLATE: "Download Template",
  USER_MANAGEMENT: "User Management",
  ENTER_USER_INFORMATION: "Enter user information",
  ROLES_AND_PERMISSIONS: "Roles And Permissions",
  NAME: "Name",
  EMAIL: "Email",
  PHONE: "Phone",
  ROLE: "Role",
  STATUS: "Status",
  ACTIONS: "Actions",
  SAVE: "Save",
  CANCEL: "Cancel",
  START_DATE: "Start date",
  END_DATE: "End date",
  REMOVE: "Remove",
  ADD_ROLE: "Add role",
  UPDATE: "Update",
}

export enum ToastType {
  Success = "success",
  Error = "error",
  Warning = "warning",
  Loading = "loading",
}

export const tempAdminEmails = [
  "wuhrlaub@teladochealth.com",
  "josh.bock@teladochealth.com",
  "Amanda.Weatherford@teladochealth.com",
  "tbartels@teladochealth.com",
  "cclifford@teladochealth.com"
];

export const TOOLTIP_MESSAGES = {
  CLIENT_EXT_GRP_ID: "Client's external group ID",
  ORG_INVOICE_DELEIVERY_METHOD: "Select invoice delivery method. No default value.",
  CLIENT_SELF_REMIT_PAYMENT: "Indicates if client remits payment directly. Default: Disabled.",
  FINANCE_CATEGORY: "Select finance category. No default value.",
  FINANCE_SUBCATEGORY: "Select finance subcategory. No default value.",
  PAYMENT_TERMS: "Choose payment terms. No default value.",
  INVOICE_PERSON_TYPE: "Select invoiced person type. No default value.",
  EDIT_DISABLED: "This contact is linked across multiple orgs and groups and cannot be edited or deleted here."
};

export const MODE = {
  VIEW: "view",
  EDIT: "edit",
}

export const STATUS_AGE_ERROR = 7;

export const priorityText = {
  high: 'High',
  normal: 'Normal',
  low: 'Low',
  none: 'None'
};

export const statusClasses = {
  draft: "draft",
  pending: "pending",
  "pending peer review": "pending",
  "pending quality review": "pending",
  "pending rebuttal review": "pending",
  "peer review in progress": "inprogress",
  "quality review in progress": "inprogress",
  "rebuttal in progress": "inprogress",
  rejected: "rejected",
  "rejected quality review": "rejected",
  "rejected peer review": "rejected",
  "rejected rebuttal": "rejected",
  conflict: "rejected",
  approved: "approved",
  scheduled: "scheduled",
  completed: "completed",
  cancelled: "cancelled",
  "on hold": "cancelled",
  archived: "archived",
  errored: "error",
  overdue: "overdue",
  "in progress": "inprogress", 
  "processing error": "error",
  "processing": "processing",
} as const;

export const statusTextMap = {
  draft: "Draft",
  "pending peer review": "Pending peer review",
  "peer review in progress": "Peer review in progress",
  "pending quality review": "Pending quality review",
  "quality review in progress": "Quality review in progress",
  "pending rebuttal review": "Pending rebuttal review",
  "rebuttal in progress": "Rebuttal in progress",
  "rejected peer review": "Rejected peer review",
  "rejected quality review": "Rejected quality review",
  "rejected rebuttal" : "Rejected rebuttal",
  approved: "Approved",
  scheduled: "Scheduled",
  completed: "Completed",
  "on hold": "On hold",
  cancelled: "Cancelled",
  rejected: "Rejected quality review",
  conflict: "Conflict",
  archived: "Archived",
  errored: "Processing error",
  overdue: "Overdue",
  "in progress": "Peer review in progress",
  "processing error": "Processing error",
  "processing": "Processing",
} as const;

export type StatusKey = keyof typeof statusClasses;

export const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

export const SERVICE_ACCOUNT = "Service Account"
